FROM golang as builder
RUN apt-get update && apt-get upgrade && \
    apt-get install bash git
ADD . /github.com/densify-dev/Container-Optimization-Data-Forwarder
WORKDIR /github.com/densify-dev/Container-Optimization-Data-Forwarder/cmd/dataCollection
RUN env GOOS=linux GOARCH=amd64 go build -o dataCollection .

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

### Required OpenShift Labels
LABEL name="Container-Optimization-Data-Forwarder" \
      vendor="Densify" \
      maintainer="support@densify.com" \
      version="2.1-0" \
      release="3" \
      summary="Densify container data collection" \
      description="Collects data from Prometheus and sends to Densify server for analysis"

### add licenses to this directory
COPY ./LICENSE /licenses/LICENSE

CMD ["./Forwarder", "-c", "-n", "k8s_transfer_v3", "-l", "k8s_transfer_v3", "-o", "upload", "-r", "-C", "config"]
RUN mkdir data data/node data/container data/hpa data/cluster data/node_group
RUN chmod 777 -R data
COPY ./config config
COPY ./tools .
COPY --from=builder /github.com/densify-dev/Container-Optimization-Data-Forwarder/cmd/dataCollection .
###USER densify
