FROM golang as builder
RUN apt-get update && apt-get -y upgrade && \
    apt-get install bash git
ADD . /github.com/densify-dev/Container-Optimization-Data-Forwarder
WORKDIR /github.com/densify-dev/Container-Optimization-Data-Forwarder/cmd/dataCollection
RUN env GOOS=linux GOARCH=amd64 go build -o dataCollection .

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

RUN microdnf install -y shadow-utils \
 && adduser densify -u 3000 -g 0

### Required OpenShift Labels
LABEL name="Container-Optimization-Data-Forwarder" \
      vendor="Densify" \
      maintainer="support@densify.com" \
      version="2.2-0" \
      release="1" \
      summary="Densify container data collection" \
      description="Collects data from Prometheus and sends to Densify server for analysis"

### add licenses to this directory
COPY --chown=densify:root ./LICENSE /licenses/LICENSE

CMD ["./Forwarder", "-c", "-n", "k8s_transfer_v3", "-l", "k8s_transfer_v3", "-o", "upload", "-r", "-C", "config"]
RUN mkdir data data/node data/container data/hpa data/cluster data/node_group data/crq data/rq
RUN chmod 777 -R data
RUN chown densify:root -R data/
COPY --chown=densify:root ./config config
COPY --chown=densify:root ./tools .
COPY --chown=densify:root --from=builder /github.com/densify-dev/Container-Optimization-Data-Forwarder/cmd/dataCollection .
USER densify
