apiVersion: v1
kind: Pod
metadata:
  name: densify
spec:
  containers:
  - image: densify/container-optimization-data-forwarder
    imagePullPolicy: Always
    name: data-forwarder
    volumeMounts:
    - mountPath: /config
      name: config
  volumes:
  - name: config
    configMap:
      name: densifyconf
      items:
        - key: config.cfg
          path: config.cfg
  restartPolicy: Never
