apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "densify.com/v1",
          "kind": "Densify",
          "metadata": {
            "name": "example-densify"
          },
          "spec": {
            "affinity": {},
            "config": {
              "cronJob": {
                "schedule": "0 * * * *"
              },
              "debug": false,
              "densify": {
                "hostname": "\u003cinstance\u003e.densify.com",
                "port": 443,
                "protocol": "https",
                "user": "\u003cdensify user\u003e",
                "epassword": "\u003cencrypted densify user password\u003e"
              },
              "prometheus": {
                "hostname": "\u003cprometheus hostname\u003e",
                "port": "\u003cprometheus port\u003e",
                "protocol": "http"
              },
              "zipEnabled": true,
              "zipname": "data/\u003czip name\u003e"
            },
            "image": "densify/container-optimization-data-forwarder:release-2.2.1-beta",
            "nodeSelector": {},
            "pullPolicy": "Always",
            "replicaCount": 1,
            "resources": {}
          }
        }
      ]
    capabilities: Basic Install
    categories: "Monitoring"
    category: Monitoring
    certified: "false"
    description: Densify Container Resource Management works to identify better supply (resource) allocations for your underlying containers based on key technical, business and cost criteria.  Any infrastructure changes recommended by Densify can be moderated through your existing ITSM framework / processes.
    containerImage: registry.connect.redhat.com/densify/densify-operator
    createdAt: 2020-08-19T:12:00:00Z
    support: Densify
    repository: https://github.com/densify-dev/Container-Optimization-Data-Forwarder
    operators.operatorframework.io/builder: operator-sdk-v0.19.2
    operators.operatorframework.io/project_layout: helm
  name: densify-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Densify
      name: densifies.densify.com
      version: v1
      description: Densify Operator that will deploy Densify Container Data Collection in the cluster.
      displayName: Densify Operator
  description: Densify Container Resource Management works to identify better supply (resource) allocations for your underlying containers based on key technical, business and cost criteria.  Any infrastructure changes recommended by Densify can be moderated through your existing ITSM framework / processes.
  displayName: Densify Operator
  icon:
  - base64data: "/9j/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAgICAgICAgICAgMDAwMDAwMDAwMBAQEBAQEBAgEBAgICAQICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA//dAAQACv/uAA5BZG9iZQBkwAAAAAH/wAARCABQAFADABEAAREBAhEB/8QAqAAAAAcBAQEAAAAAAAAAAAAABAUGBwgJCgMLAgEAAgMAAwEBAAAAAAAAAAAABAYDBQcAAQIIChAAAQMDAwMCBAQFBAMBAAAAAQIDBAUGBwgREgAJIRMxFCJBURUjMmEKFhcYkUJSYoFyobHBEQABAwIEBAMECAUEAwEAAAABAgMRBCEABRIxBiJBURNhcQcIgZEUIzJCobHR8BVSweHxFiUzYiaSsrP/2gAMAwAAARECEQA/AMaAbaSmM4ygspVGYQ+2t5TwfkJCviH0KCG1x23yRxaHL09v1K38b54KUBLieUFIkTMnqfIHonp3M4+a1uKUVIVchRggRA+6OoUR1VbVOwjAWUlRJUDzITzKifnAAA2P1JI8FJ9uuKEmQek+eJmCI0mwmPL99iMBm0KUeXIE+P8AUBt7BSdhuNyNt/P79SJk774nWoARFsGiWglJS4pB8J22KVAAg8APvt9+iwhKUw4RsMAqcKjqQD+98A3IjalEDb29wNvJ+p+/QbjaSSOmJ0VCwJwKZggN/lhKuJ/SSOR39/8AA/8AXXAyNEJ3HTEDlUdXPaflgQmBwHren6aEpIUooO52/UlSfv8A436jU1CdZEJxEavUfCmVE9/ywBfb4glXE/QAJ99h4Sf+RB6AeMCTEYKaXJgT++uO0WKp0/OjYAJ2HjYBQ8eTuNtj9+hgrVZYGIn30oHKb46y4SkAIbKCle6dv9Xy/MSD7Dx7eOhqgW0oiMeKepCuZcyP8Y//0MVglqOzaVLGyvHuOKvoQfcgDrc1vwQgA4wT6Okc5A2wNS96g/MP6ynz7/OCR53+nnx1IFyJPXApa0nkG35YEKQVcltoHBJ4hBVvsUD9IV4USAfcjz1LJIsLfp0xCFBMJWeY9fX8P0xJnR9pBznrrzfA046c6VbVey9WbOvW9bfoV23THs6l1uBYdNaq1ZpMOvz40inxKxLivgRBKLEZawQ6+ykFYrcyzJjL2Q4/qj47SAfzG04uspydzNnihtQS2IBsCZKVKFiUg/YMyoRb0xLLFfaE1yXdqvtXR7lzD946WMmXvQL+q9oXPnCy7iViy4Jdh25PuJ6nUy/bMZr1tVuJVWKY80ibS5dQEdaN1NLKkoVhHvFe83wX7tPscrPbZxVRV2acOZbW0TFRT0amk1QRW1KaUPN+OpLKi0paV+C440pxMwpEKIYck9nGZZxnCMnW422p0K0KlQBUltbkE6FEAaIUQlQ5gAokYI9TXax156PG5k/NOnS712bBWpbmUcYtf1Wxr8MVKKZ064LSjS6nbTDiUEj8ap9N4jweqH2Fe/Z7o/vFNs0vs041y1PE70f7Xmh/hWZhXVKWKwoaqDe30OoqQemK3if2U8a8PLW65TKfo0z9Yi6YAkklKilCenOpKyfu3EwQedalRG2t9h4c9RCRycUUApLzmxQ40s/T336+sal4LT4SpBBv0M+eMpbbcYqC58IJsL3gbgj5RhPrhNvKcWgKAQN0ttbH5wP+ZO6eX6vc7Hx0vvFJUTePLFumpW2lKVRfcnt8Ovb8cDoEJDqFjmGXm/0oUFBB/wBRKiduPk7dQJ0rm8KGBauqUhQtqaO56/DBmmiPz4a5jCUJYSl91xJDriooQQlTq+IU4804vwncbgeeh3EKcQXEfZ67mP1wEczapKgU7sl0kAGwCp6Dokgb/LH/0cT8daDsSdlEeSf2P0HuetxUG9zbGGupULDbBgpTYQgbKKyFclFQKFfP8gSAAUcU+/vyP26jcWhKQLlXfpvb0j4zgMBZUTYJ/Ha/r5bR54FRn0cglStgEgkkAEqG/JA2J5NjwRv5/wD3puoTME2/c4geaVEgXn/B8j36f00U/wAMEqnHvF4AaagvM1VrDepxdRnqml2NNZdsel/hrDFO9BHwDsFpLgcc9Vz4j1E/Kjj5peLlsqylICSKgE6lTZQKm9ICfukDc31SNou1cBF01j0qBY8RrSIuD4dTqJV94ExAgaY6zj1EHmGJLamZLLUhlfhTTzaHW1f+SFhST/jrHM2yjKc+y53KM8paetyl9Ol1h9tDzLiTulbbiVIWnyUkjGvNuONLDjSilwbEEgj0IxAGNW6NVZ9Q/BqnCmNs1SfGdZiPpC46o09+O4w7FPB5r0HGyjYpAG3jx1+Mj3kfd+9r/sP43zXL/ahwjnPDlC9X1K6NVTRrbo3WHXHHKc0lUhKqRxHglGgMuq0iEwCIGv8ABHtF4G47pA7whm9DmK2iUOpaeSXW1tq8NwOtEh1BC0qB1oEkTtfHkvagRI/uH1HtR2o6Gm9QOc0JaQ20zHDP9Vbt4tMtNhDLKWR4QhISlKdgAAAOv25+yiodV7H+ENair/xDJLkklX+10kkqJJUo9SSSTcmcfCnGv0ccU1alyCXunQwOnY4aGApgySo/IlJSgoKuK1kfKNtvHDl9B5PTm2+guSY0j4YWaoOBnSLkiZ6D+/4YUkiF8YEGnlrdCX1Pbq2dPyjdspV5W8t37eD/AI65UOB2S2RN56fh3JxSs1P0ckVmqCUhPb1noAPjgDR3K0uDNZjtKjgyWY8nipwPOBHhCixx2DZJ2A3Hnx79VaHX1IUlNrgH/GCsxRliappx5QXyFSZiBO41d/htfH//0sRqHCdg2T52PHlv5A8qKleE7+T9hv1ta7nSOvT9/sYxpSALr+cfv++BbMoqJRvt43I+nE+CpP39/p5O3QS1j7IwO4xA1YEpd+bcE+D9Pff7/tv0IXVBVtpxAW7Qe2Jw6AdbWVu3fqgsjVfhu3bDu++bOot122i2MiRa0/adVtu96c1SrhiPqoFSpVYpc9URpJiymXV+g6CVsvIKm1ea6g/iNP4SlEGLRYbg3EHsPx74IyjOhk9Tr06mSoFVpVICkiOZIJhatyLxe0H0uO1R3qLG7jOn+p5dvXEVX0+Vy2MjT8WXBThcbeQ7Rm1yk27QK7Jr9Gr8Gj0SrwqFMTXAlDc6nNOsFBC1rGzil1fBuZrZU/RFDyUqI0zpUY7A2PzB/wCuOZ57e+BeF+IWeH+JFVFKqopkPJf8NS2EhalJ0uqRK21J0gk6FNQr/kMGGVz5qjxnoytC8dUGV4Vy1TGtmXjGpldcsalMV642oWRbxVbdIrUCkPzKcuqUyFIqbUiS0058T8Nuppp1xIaVknv6exPjn3kvc64m9hns/do2+L8yOVvUya11TNMVUNYxVOtF0IcDLrqGlIbWpIbLkJcWhBK0/Ifu255lPD3vH0HE1dBoPHzUeIjTJQ+3UBtUqKZbOpKrkWMgTbHnK35WrZvnNObrupr8iXbV4ZcyjeFtyHIT8GROt2678r9wUibNgygHKdJfo89lxyO4ebLpLavKSeti9m+V12Q+zvh7h/PEJbzfLuHcrpKhCVBaUP0tDTsPpStPK4lLra0pWnlWAFCxGN29oWYmpzt+uyhWthx4lKlWMCwgXNz62vhGSqZb0RyRIhOLkpZW26UlHrOBSRtxQtPhsoWoEg7+fbpke+jIJU2ZjCqxW5xUIQ1UgIUoETMCPMdZAwR0626nGaVMCn3FrcD5dV6jrRZlcjICnSBvJilKVFBASAfB38dV6GnANUkkmfnvfuMW1Zm9I8rwNKQ2BpgAAgpjTb+VVwDcyLjC9t+gvVBuoMJqqKa+tC3Iq4ryuLq2UBxlbofDg3D4CinYpBJ2/Ytlkr1DVpPSD8t/PCrmmZop3GV+B4zYsoLAsDZQER92QDubT5//0883a+7VsvuS2bq0yLO1S4p0qY/0d2/YF1ZIvHLVrViv2+5bd8Q7+nya49UabXqBCoNKtWNYTqpjkla+YkNlAAQs9aNnGdPUJQGkpJVq3BO0dlJ7+e3zRMuyVmtQVvKVsCNJiJKk9Uq/ltEb/KVtQ/h/78yZY17Xb2+9e+iXuTVzGtGfui9cL4EvdFDzezQoyQl6q21aVQq9xwa4StaWWmJE2nGbIcQxGU7IUhpVU1xG5tVo+rJsUiL9eYqUDbpYdyNxPU8LMqSVUiyl8J+8dQI6ApCUkCfvCSOiVbYouRDajuOJejuxHIDsmHLZlRH4E2NMjOqjzYtUgzuMqDOp8tlxh1pxKFtOtqCkg77ODQpnUJqGY8IjeIn1B2IMjpEXGMvqxWMPKpX5FRIlJIMdtJTYhQIUDeQRB7jm0traUtgNBaELWSt9tLfJCfVRIU6vdvhsg/IfCj8u/nqW2mURqHc/I/2+GK5SlocCXdWkkCySTcwUxvN9+m+LJdDfdH1N6C6bUrRxZWMcXNia6Lnfvi5MS5ItZmo0ms3TNiwqLLqlDuiiSKTeFq1SfCpzDLhiSn2ODSD8PyB3Lpn3KdM606VSrSRuTa0bX7T6DCLxdwFkHGJD2a01UMzaQlpFQyuFNtp5oWhQKHEgTGvQZJlRGLQtZXeixBrH0E5hwZcuHb8wnnK4KriupUuPDq1Mv7FNaXa1+0av1wU+6kfgt02wGaVEeeYbqlOc9ZQS16vJQJKqqo/R1IeSUOAi4II777j4jGbcM+y2o4e4vpc3y2tZrcpCHgUqQpp9IWhSUgoMocMkA+EtQFzNsUmaar+xJZGecOXtnCzv6o4NtnI1q3JlzGsGFCmSb7xjDmJVeFsNw6lOplLmP1akqWUoflxmioAF1v8AUFfMHFPU60MKSFKSfSCCL79YJxr+Vts0Gb09RmLLi223UzsTKXEq5ZKSDpCkC4urfriyzDOjLHvco7hWasMdu6RbuG9MX4Tc2brTunLrdeTAw9gCi0+z6fVl1ykzqxUrqqktOQbhXT6bGdqK9o6g85KRGZKhRnMXaChT40KeMARHa07b3jy+ALMOEaLivih5WXlbNAnUpYWTOoKIMElY5QUBVzzG+5UK99RdrY5wnl2v4rxLqPxvqzsij0qhTqbmnEsKo06zLjkViM67U6LGpVZnVGa3OtiU36EtYfdYcK0LbV5IE1FmKqlvUoQfUEbkR1+Prim4l4OayWrLTK9aTvKSFDlSqTypHMSQmBPKZ7lDWs1HDpjJDLb8jm62FPpMpSSDvxTulfAcTx2GwA6sWn0punvhOrcrddOl+J028vOP64//1K2+xoor7WH8SKdth/ZpYoB+hP8AT7Upv4/bpwzcldXTWjnI/wDjC/lACWCOuhP/AOjmK5ezNdl9447qXbvrmMp9QpNx1rVHiuwqu/Ri41IrNgZAqf8AKmSrfnloH16BPsiqz/ikuAttoR6uwU2FJuc8p2FZeS5pCgFaT1JCFHT5iQFEd0g9BhQyOtqVZspCSookSkmQmXW0FUdFaVFM76SemNalY7W9jXBn/uza8sL6OMSa9s1y9fVdw1p70154vyzbF05WBccayrAu7P8AnPIFOuy4rZoV+VReULprEZuiqdMpAjrVH4rlvyI6mK2rabbp1PKQ0UJVYkRskAEJURYFUgHeBBJlvFLSuuvVLbKFvBS2yYBKhzLIMrSCkkhASSkagCqUpTpYbUp2tbYrGN9FusfOWh3TboU1L2l3CtLWGtTGmjAd+4/vHTPqcwFlTOGObLiXrR8ZWrc900u1qg1XLtap8mlh5ct+mR6l8aqRHchrjEsZg814jDbqnG1tkg3BChIupQSTCYVMf9R1JFqMrpavwnainbQWlgAK0mERqslKlpAKpbKAqDPiXKUjBBnrMPbu0397yX25bL7T2jq/MU5Y1BYExPnK/srWU3cV90y5M7W1YqIn9u1KRHbsrDWOsd027ac4aPEp3qVmc3PkGSw7IS6O6dmtqqFVYqpc1pSSBqP3QokHefsiLgcxO6YVHU1OX5dXt5eilb0KWIhKba1tp1DbSZWZgE8iRIBGlfYT7behzDmqfu7YmwthTS5qB1lYYy9j5rQtpd1235NOGI+Ib1sWwb/uCFbdLrtSeVfFSodZuys0llye5KmR41JpEd+ZDamSJbstQ7mBoaerdU59EWkypO4IEAFUK0gqBMxMEpAIQMAsfwcZrVZXTeB/FElJ8NSQAoKWSQE60eKpLfhkgmApWsnU4qWmu/EFNtHXd2jHs29pF7tuasKhrmxpa+S7qwo3ZMnQRqFs1+v1P4yg2lTbSuS7KVByNBYRTpcSMtbb3wC6m0+uex8K5HBQ6VJeSl4rb0KIndR0H0PnJSNoFpJizKlSHqNaqMId+ksJJFkto8ds/ZGtAk8ulDigdQUuCEpTYP258uW1jPvH96/SvZ+mzTLTbTsO185ZwouQ4+MmIOVlxJNM08wJGB5NdpsuJSU6epNSkSKuu32IbW9XlPSPU/MKQG/rdp23FKUYKU7+RM+vn2/Gzy5umos0qKdhtsFaHnSdIBEOJQEAj7hAkpje8mYFI7dwYP7s3Z31m5ts7RTo60oa0u3XfuOs91GnaOMNwcR0e+9K023Za7ianQXalV65Kh0+24d2S6ghyXIhNy7cgOIDSlnrjTrtM6kuKOiJ3JtANhbcct7TPa3muoKHOaJ9FK02agrKSdATzalIlShqJ0q+tMEKKNII5jLW9weyMc9v/s09vTFDeNLBGvHXfV52q/J+VKpatBrGUsZ4F2p9zWvj2m3O5FNx2pS6lGuK2aaGUPpYdNKrbKm+b7hSQmsrF1kMKUADEbgXvMWIm09oxW/6WyBvI9OYMNOLWJ1gaVKkaUEFXOklIDhTsF6rRbH/1aYey9rx0M6VcAdy/Tnrnn59pdj66cZY1xTTqpp8s6jXRdNMt6l0TLtGvicJ1emCmUGrx2r6hmnKfgz2XleqVoAbCVu+dNPLUw6yP+MqOyz/AC/yAkbbyPI4VMpqmG0rQ4YOlIuUi4Us21KE2ImJ/WQmHe4b2S+2VXZGbO27pv1daqNY9NoFcouKsta66zaNv4vwpLuSnu0So3DRLXsFymzqpVHaTIWw/wCjSWKi9EW7GaqsNuS8VArTmOaLioUAxMEDWkAb7L2nbUASethaQP5XlTKltD643kBsqUb7+HAMSYCylN7GdmO0v9zXA2QtNGpTQ/3VqDmnJuG9SGouqaxqRqRwC3az2dcO6p7kdTJu68HLMrwj21dVq3fUUqe9FpDiqcibUI3wj7clh2EfXUbjJbqqA8yEBJFzYK1CAJVAVcC4AASeUQaHK83o6sO02Zp0FbhUJIAUCnQedWlIUWyULnRJ+sRzrITyrWp/tRYBuLRvZui/A2Y7ppOINX2H9SOojXVqSta2Dqcuaz8f5Bt65KnirDNg2rOg06gWc1S6UfyZAp6pTjIZQ2tcmRNMTlNmVQhx+pUEktkAAGYuYuAoSbERGkkCSbSKzfJKV1mjpQSA8mQFJ0bABRUFqbNuaSrV4idSylIAUF1L60cC5r75UXuW2C1f0nT6dTulnMVVh1iz0QMnwLDwlR8QQr5mRrJdrC4v4yuTZ85NOYE/1ZrSEcvR9TZNlQ5JUIyhRbAVUraWCL2B1QbgQbjoTvbuvZxxZRf6jaYqFlFE3UNFKwU6VqJQSjUlRBA0KJkpQCUkqmQJkZ37jPam1T6mtf8AG1b6aswzMO6osl2DkzTZrNxdj+1kavcCVS3MTYutC4rRr1rXPVajDfx3MuKwXnokaN8a4YdRnpkR1CZHcgV5ouIKBtlJjw0JICYJG53AGoqvqkDaxsAFWgzXgzOXqkJMvOFJWvWhJVYWDhX4eiEhMahCro5+ZCyg91LR1iKwtAWkjThUNZWatM2mzX1iLWtmHUNqvcoVWyrEpWL6/wDi0XFOn3GlKmKco9rIADqWXXaalkKlstNPqnvPNwN5PmDgXUaWwFNqTbVfVJ7STJA2I026AYAzbjDhulcYoXHHvFRWMuQS2oJLfhp+0FFtKCkKJhYV4hKiAFEn706d1rShiDu0dznW9eTOXU4R1hYfyDYGJ26PjxNTvlmv3YrEfwS7ttYVyOLfgIFlTuTnxLvHdnkE+oeMbuU1Yo0IIGrxEn72wTHaRfuMR0nGuTO5686hSvD+iupklsAlToWIJcCVW/lUTOwscMx/DL0nMltdxW0bQpmFroyZgDUJhLLennU56tn1Gs4mZsNm0m7sTOu+v1KnLsdaaRc1Hh01ynyX/i5cS41x0NLMlKF+M1pG2GE61aahKBbvBAsfIk2F7zEAkT8FZrUZjWvONNlzK3X1wo9NYK1AoExqSEErUNADZQFalpSqP3ep1B2zrZ7h+oDIVuvpmYdwy/TdKunxmjuRv5apWPsIyKhb1WqVvIZS1FaoN15LnV2dF9NPBcN6MUAhKT03cO8Ps/wwVb+ovLP/AKnrM3Bk6TvJSD2wie0HjasHESMry5TYYaGpQ6rSQCgApJChoHjIIgpDyknYz//Wwtx3QUEuAqBBG2/E+R8pIHzFJB8be/WipXqbJWJt+/hjPXkEKhFv3+eDWnOobcVya5cF7FCuRSpGwBV8qkr2SDuBuN9tt+umVJSSCnY/vz/XANYhS0CFRI37H42/C04XNJWw2UpkuBttalfmBIG+52acd334FSNt0jcDf/vothSBZwwJ/wAE/phWzBLqpUyCVgbfmB3vsTv+GHZoVPiVl1MWHEElc1aGVyFKPohllHqSEp2APqLA2QAdz0xUbDVaoNNp1ajE9IFyPU7DCBmlXUZagv1DmhDYJCQLyTCT6Dc9MdaqudbiFUuDCpfpL+IagyltgvtKU2pHqPuO82kJQDyAI3Cj52O/RtSHKFP0dlDYBBCD1Fus2t54joU0ucrFdVOv6xpK0g8pAIMJAg32sdtpGG2qFTrIiPRnaolch9AQ6Gkji2laOKnoYVsuJIdUeLgbVsU/t7q9XUVKWlNKcBdIvHSRuOxOxg7Yc6Ohy01CXkMEMpMidyQfsr6LSBdOoTPnt0tCdWaO+Y1MmuIaeZUExZL6hGDj4A9VDfpOH1xtyBJ8Hz0BQuvsq8NomI2JtJ67fHHniGly3MW/GrWwVpUOdKRqhPQmRy9LYea3bamuSJVUqNVelVVEhv4NKQp+Gv0Ry8R+SWChtajsVbEbe58dXdPQuKUpx1ZL827fLbGb5xnVMhpuho6dLdAUHXMJWJ/7XVJAvEg9sS8xv3BNaWnDDF46dsC6jMgYixHkGtVuuXtZdj/y9S3q5W7npVLoNwVKLdxoj960CbWqPR40d9VNqUM8Ghw4KKlESry2jdfTUPoCn0wAO95223JwxcNcSZzl9A5QUrsUTnMDeU8oTaIMBKUgdLXBFsQkn3C1TIjUanNpbTHbZZ3G/CM2whHpstNciELbKQUL8rO3uffpi+mIYaSllIkAXIsB2juOhwHSZQ5W1Cn6tRKlqKvNRJMqJi4PUbeWP//XwwRm23GfTGxc3Ts59ACPBTv5ICv+gOtLabQtrw/vWg/p8cZy+tSHNf3O364PKfGkxObHFbnqhBWhRKUPeiStC1DwFpaKiUj23PXpuncYlsySd/OLj5dMVlXUNVADkhIEwRuJsR5T1wubXtZu4XpMeZVYtHaRCmyWnJolluZNiNerGokJMSPKUmp1VX5bCnEoYSv9a0J89E0eW/TFlK1hCIMTMEi4SN+ZWw6d4wuZtnP8NQHWWy6sKAIESEmynFTHIjdQHMRsDh2bJlItFPryYy1iW09TWkyylZW2jZayhrmn03Wyvw6AAD45HyAx5M4MqOtxJOoaRPX4dI74zriZhXEJ8JlYBbUHDptBNhJ6g9Un1jBfV6tDr0Gpbbx+Dy0lW4Sv0gV78AkkJbAUOQG5P36iq6puuacI5QCZ9P0798F5dl9RlNUzPPKQe4m287nt0wmqXApbjaUBSXAhO4S6n8sOlPyBK/Kg0Dtt7g+Oqlqnpikabx37/pi6rquvQoqIKSTuDeOtu/frgzkSYDWyClHJSUbutEjde+5QQghSQhA/V7dRv+CD2J/P9MBNMVbnMCYBNj2737npgzavNdOX6oWluGWlNuNpUhSFJ8J3Ty3JUrbySSSeuxXKZVqJ+qiCOn7/ADwCvhpNYnwyCqoCpBMz8cJCsXY2/wDn8wlgKK0qcVxcaTv/ALtwk7eOJ+m/16Gdrkk6x9ne/QfvbDFl2QLa+qiXYiBcH99cImVX1OSEJX66GH1KXy4cEu8FFKlNLUOJ4qBSSncJV+/jrymuJcCSSEq/H0/LDOxlHhslQ0lxIjeYnaR+InceWP/Qww0phKShTrm3lRbOwKFJbV52G+58jz1qFCwhKgparXI7GMZzXuqUClCe0974VjdaZbJ5hocW0tJTwClupLgWVpUQr01pUgEndO4IHtuOj3KxoG+mQI23vM+vytbFCvLXFJ5dVzPkLRHSRfzvfzws7cuyLCleqphtCEj50JP5iyQeRQokcHh/uBA8dF0WaMtPFakgJ7df7HCznOQP1LGhKiVHY9B6jqPLH1c18R6rNaIb9JptsFhtXBShy8ekpTezex25E+Dv0LmmboqngY0pAsP6W+eOsk4XdoKZV9ThPMbx6ib+XpgveuJaYaUN8UpKgspRt85I33dB+VW336FVXK8LSkQPz9cFtZOk1BUuSYi/T0wXJqrjkdckei2yJaKe2WZLQkB5THxSd4vMSTGCBsXeJZC/k5cvHQvjqWkrEAatNjeYnbePOIm0zg45clDgbOor0FZlJiJ0/a21Tsmdcc0RfAtiSl5CkzJKG1BB2WEhJP3BUjfwd/P3J69I0rBDhAVG+BXWC2oKpkEpnb/OAlSe+HgvNsvb7rSPmUlSlpKgeY5eEgH2+u/UT6EtslKe/rgiib8aqStxPTzEeVt/PCTjzZ7LrMmBNMaZCeUuNKSW1uoc2UgKShxt1kAoWUnklQ+bfb2PVc145IWwoJcSZCuv6fgcMS2KYgt1DeplxICk3iN9wQdwDYjbffAOI0WlbL5uJZKUo5Er+Xfx6YWpXAFRPgeT/wDJ6Vktq55MfH5dv64mqHNaZTAKvhfzjf8Apj//2Q=="
    mediatype: "image/jpeg"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - densify-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - densify.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: densify-operator
      deployments:
      - name: densify-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: densify-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: densify-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: densify-operator
                - name: RELATED_IMAGE_DENSIFY
                  value: registry.connect.redhat.com/densify/container-data-collection-forwarder:release-2.2.1-beta-2
                image: registry.connect.redhat.com/densify/densify-operator:release-0.0.2
                imagePullPolicy: Always
                name: densify-operator
                resources: {}
              serviceAccountName: densify-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Densify
  - Monitoring
  links:
  - name: Densify
    url: https://www.densify.com
  - name: Densify Container Optimization
    url: https://www.densify.com/solutions/container-optimization
  maintainers:
  - email: support@densify.com
    name: support
  maturity: alpha
  provider:
    name: Densify
  version: 0.0.2
