apiVersion: apps/v1
kind: Deployment
metadata:
  name: densify-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: densify-operator
  template:
    metadata:
      labels:
        name: densify-operator
    spec:
      serviceAccountName: densify-operator
      containers:
        - name: densify-operator
          # Replace this with the built image name
          image: registry.connect.redhat.com/densify/densify-operator:release-0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "densify-operator"
            - name: RELATED_IMAGE_DENSIFY
              value: "densify/container-optimization-data-forwarder:latest"

