apiVersion: v1
description: Densify Container Optimization Data Forwarder Utility
name: container-optimization-data-forwarder
version: 1.0.1
keywords:
- densify
- container
- optimization
maintainers:
- email: gbarsky@densify.com
  name: gbarsky
details:
  This Helm chart provides a Densify Container Optimization Data Forwarder tool