apiVersion: v1
description: Densify Container Optimization Data Forwarder Utility
name: container-optimization-data-forwarder
version: 1.0.2
keywords:
- densify
- container
- optimization
maintainers:
- email: support@densify.com
  name: support
details:
  This Helm chart provides a Densify Container Optimization Data Forwarder tool