#################################################################
# Global configuration defaults.
#################################################################
nameOverride: densify-forwarder

# application image
image:  densify/container-optimization-data-forwarder:latest
pullPolicy: Always

# application configuration
config:
#===============================
# densify server settings
#===============================
  densify:
    hostname: <instance>.densify.com
    protocol: <http/https>
    port: 443
    user: <username>
#    password: <password>
    epassword: <epassword>
    # Set only the above username and (e)password settings or this Secret not both.
    # Secret must contain 2 fields username and epassword that will be used to connect to Densify.
#    UserSecretName: <name of secret to use>
#===============================    
# prometheus server settings    
#===============================
  prometheus:
    hostname: <prometheus host name>
    protocol: <http/https>
    port: <prometheus port>
#    clustername: <cluster name>
#    interval: <hours/days>
#    intervalSize: 1
#    history: 1
#    sampleRate: 5
#    includeList: container,node,nodegroup,cluster
    oauth_token: /var/run/secrets/kubernetes.io/serviceaccount/token
    ca_certificate: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

#===================
# proxy settings
#===================
#  proxy:
#    host: <proxy host>
#    port: <proxy port>
#    protocol: <protocol>
#    # <Basic|NTLM>
#    auth: <auth type>
#    user: <proxy server username>
#    password: <proxy server password>
#    epassword: <proxy server epassword>
#    # NTLM authentication
#    domainuser: <domain username>
#    domain: <domain name>
#=========================================================
# controls whether contents are zipped before transmission
#=========================================================
  zipEnabled: true    
# Name of the zip file that archives the content
  zipname: data/<zip file name>

  cronJob:
    schedule: 0 * * * *  
    
  debug: false

# If you are running Prometheus setup with Authentication such as OpenShift then need to set to true.   
authenticated:
  create: false 

nodeSelector: {}

resources: {}

tolerations: {}
