apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: densify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: densify
subjects:
- kind: ServiceAccount
  name: densify
  namespace: <namespace using for Forwarder>