apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: densify
rules:
- nonResourceURLs:
  - /api
  - /api/v1
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
