apiVersion :  v1
kind :  ConfigMap
metadata :
  name :  densifyconf 
data : 
  config.properties : |
   #
   #  Copyright (c) 2018-, Densify Inc. D/B/A Densify #  All Rights Reserved.
   #
   #  For Densify Versions >= 10.2.6 and Client >= 1.2.5
   #
   
   ###################################################################
   # \ HOST definition section
   #  Specify hostname, port, protocol and endpoint definitions
   #  Credentials definition section (API access information)
   ###################################################################
   
   host <instance>.densify.com
   protocol https
   port 443
   endpoint /CIRBA/api/v2/
   
   user <Densify user>
   #password <password for Densify>
   #epassword <override plaintext; use result of Encrypt.jar>
   
   ###################################################################
   # \ Specify settings for Prometheus used by the dataCollection
   ###################################################################
   prometheus_address <Prometheus hostname. Using the internal service name is recommended (i.e. “service name”.”namespace”.svc)>
   prometheus_port <port|9090>
   #prometheus_protocol <http|https>
   #cluster_name <optional parameter that allows you to specify name to show for cluster in Densify. If not specified will use the prometheus_address>
   #interval <days|hours|minutes>
   #interval_size 1
   #include_list container,node,quota
   
   prometheus_oauth_token /var/run/secrets/kubernetes.io/serviceaccount/token
   ca_certificate /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

   ###################################################################
   # \ Client transfer settings / options
   ###################################################################
   
   # controls whether contents are zipped before transmission
   zip true
   # when directory transferred and zip active, will use this zip name
   zipname data/<Cluster name or prometheus server name or other name may want to send zip as>
   # will prepend transferred filenames with this value
   prefix Container
   # default filename or directory to upload when name not supplied
   source data
   # add timestamp info to filename if set to true
   # [<prefix>]_yyyMMdd_HHmmss_<filename>[.zip]
   stamp true
   # specify amount of lines to tail when outputting log data
   #tail <10>
   # allows client to use different API calls for some operations
   # differences can be seen when using debug mode
   #v2 <true|false>
   
   ###################################################################
   # \ PROXY HOST definition section
   #  Provide information for proxyhost access
   # \ Will only come into play if proxyhost field defined
   ###################################################################
   
   #proxyhost <proxy.host.com>
   #proxyport <port>
   #proxyprotocol <http|https>
   #proxyauth <Basic|NTLM>
   
   #proxyuser <username>
   #proxypassword <password>
   #eproxypassword <override plaintext; use result of Encrypt.jar>
   
   # Following are used for NTLM authentication
   #proxyserver <domain user name>
   #proxydomain <domain>
   
   ###################################################################
   # \ Pre-run command invocation
   #  This command will be called before client execution
   ###################################################################
   
   # Linux sample - data collection using python script
   command ./dataCollection
   args --file config --path ./config
   
   ###################################################################
   # \ Debugging options
   ###################################################################
   
   #debug <true|false>
   #internal <true|false>