apiVersion: v1
kind: Pod
metadata:
  name: densify
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: densify                           
  containers:
  - image: densify/container-optimization-data-forwarder
    imagePullPolicy: Always
    name: data-forwarder
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    volumeMounts:
    - mountPath: /config
      name: config
  volumes:
  - name: config
    configMap:
      name: densifyconf
      items:
        - key: config.properties
          path: config.properties
  restartPolicy: Never
